# Generated by Django 5.2.6 on 2026-02-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0003_aboutcard_highlight_service_siteprofile_sociallink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='about_intro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='contact_intro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='experience_intro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='branding/'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='features_intro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='header_cta_target',
            field=models.CharField(default='#contact', max_length=120),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='header_cta_text',
            field=models.CharField(default='Let’s chat', max_length=60),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='process_intro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='services_intro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='skills_intro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='work_intro',
            field=models.TextField(blank=True),
        ),
    ]
