# Generated by Django 5.2.6 on 2026-02-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0004_feature_processstep_siteprofile_about_intro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='favicon_url',
            field=models.URLField(blank=True),
        ),
    ]
