# Generated by Django 5.2.6 on 2026-02-06 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0005_siteprofile_favicon_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProcessStep',
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='process_intro',
        ),
    ]
