# Generated by Django 5.2.6 on 2026-02-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0006_delete_processstep_remove_siteprofile_process_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='branding/'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='label',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
