# Generated by Django 5.2.6 on 2026-02-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0007_siteprofile_logo_alter_sociallink_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media-assets/')),
                ('image_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='hero_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='logo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='show_contact',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='show_education',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='show_experience',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='show_features',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='show_projects',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='show_services',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='show_skills',
            field=models.BooleanField(default=True),
        ),
    ]
